name: rp2 port

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install packages
      run: source tools/ci.sh && ci_rp2_setup
    - name: Build
      run: source tools/ci.sh && ci_rp2_build
    - name: Upload build outputs
      uses: actions/upload-artifact@v2
      with:
        name: pico-build
        path: ${{ github.workspace }}/ports/rp2/build-PICO
