name: rp2 port

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install packages
      run: source tools/ci.sh && ci_rp2_setup
    - name: Build
      run: source tools/ci.sh && ci_rp2_build
    - name: Upload build outputs
      uses: actions/upload-artifact@v2
      with:
        name: pico-build
        path: |
          ${{ github.workspace }}/ports/rp2/build-PICO/firmware.bin
          ${{ github.workspace }}/ports/rp2/build-PICO/firmware.elf
          ${{ github.workspace }}/ports/rp2/build-PICO/firmware.elf.map
          ${{ github.workspace }}/ports/rp2/build-PICO/firmware.hex
          ${{ github.workspace }}/ports/rp2/build-PICO/firmware.uf2
